INSERT INTO PROJECT(ID, NAME) VALUES(1, 'Eikelia');
INSERT INTO PROJECT(ID, NAME) VALUES(2, 'Panorama');
INSERT INTO PROJECT(ID, NAME) VALUES(3, 'Brodhold');

INSERT INTO HOUSE(ID, NAME, PROJECT_ID) VALUES(1, 'Noomi', 2);
INSERT INTO HOUSE(ID, NAME, PROJECT_ID) VALUES(2, 'Aurora', 2);
INSERT INTO HOUSE(ID, NAME, PROJECT_ID) VALUES(3, 'Tuva', 1);

