CREATE TABLE ENGINEERS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(65) NOT NULL,
LAST_NAME VARCHAR(65) NOT NULL,
EMAIL VARCHAR(65) NOT NULL
);

CREATE TABLE CREATORS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(65) NOT NULL,
LAST_NAME VARCHAR(65) NOT NULL,
EMAIL VARCHAR(65) NOT NULL
);

CREATE TABLE PROJECTS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(35) NOT NULL,
ENGINEER_ID BIGINT NULL,
CREATOR_ID BIGINT NULL
);

CREATE TABLE HOUSES(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(35) NOT NULL,
PROJECT_ID BIGINT NOT NULL
);

CREATE TABLE USERS(
USERNAME VARCHAR(35) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(100) NOT NULL,
ENABLED TINYINT NOT NULL
);

CREATE TABLE AUTHORITIES(
USERNAME VARCHAR(35) NOT NULL,
AUTHORITY VARCHAR(35) NOT NULL,
UNIQUE KEY AUTHORITIES_IDX_1 (USERNAME, AUTHORITY)
);


ALTER TABLE PROJECTS ADD FOREIGN KEY (ENGINEER_ID) REFERENCES ENGINEERS(ID);
ALTER TABLE PROJECTS ADD FOREIGN KEY (CREATOR_ID) REFERENCES CREATORS(ID);
ALTER TABLE AUTHORITIES ADD FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME);
ALTER TABLE HOUSES ADD FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID);

