CREATE TABLE PROJECT(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(35) NOT NULL
);

CREATE TABLE HOUSE(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(35) NOT NULL,
PROJECT_ID BIGINT NOT NULL
);

ALTER TABLE HOUSE ADD FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);

